name: rcloud

services:
  rcloud-simple:
    image: rcloud-simple
    build:
      context: ../..
      dockerfile: docker/common/Dockerfile
      target: runtime-simple
      args:
        - RCLOUD_CONF=docker/dev/rcloud.conf
        - RCLOUD_RSERVE_CONF=docker/dev/rserve.conf
    ports:
      - "8080:8080"
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

  maint:
    profiles:
      - maint
    image: rcloud-simple
    entrypoint: /bin/bash
    build:
      context: ../..
      dockerfile: docker/common/Dockerfile
      target: runtime-simple
      args:
        - RCLOUD_CONF=docker/dev/rcloud.conf
        - RCLOUD_RSERVE_CONF=docker/dev/rserve.conf
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

volumes:
  rcloud-run:
  rcloud-data:
