name: rcloud

services:
  redis:
    image: rcloud-redis
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-redis
    # ports:
    #   - "6379:6379"
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

  scripts:
    image: rcloud-scripts
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-scripts
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

  forward:
    image: rcloud-forward
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-forward
    ports:
      - "8080:8080"
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

  proxified:
    image: rcloud-proxified
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-rserve-proxified
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

volumes:
  rcloud-run:
  rcloud-data:
