name: rcloud

services:
  redis:
    image: rcloud-redis
    build:
      context: ../..
      dockerfile: docker/common/Dockerfile
      target: runtime-redis
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

  sks:
    image: rcloud-sks
    build:
      context: ../..
      dockerfile: docker/common/Dockerfile
      target: runtime-sks

  scripts:
    image: rcloud-scripts
    depends_on:
      - redis
    build:
      context: ../..
      dockerfile: docker/common/Dockerfile
      target: runtime-scripts
      args:
        - RCLOUD_CONF=docker/stage/rcloud.conf
        - RCLOUD_SCRIPTS_CONF=docker/stage/scripts.conf
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

  forward:
    image: rcloud-forward
    build:
      context: ../..
      dockerfile: docker/common/Dockerfile
      target: runtime-forward
    ports:
      - "8080:8080"
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

  proxified:
    image: rcloud-proxified
    depends_on:
      - redis
    build:
      context: ../..
      dockerfile: docker/common/Dockerfile
      target: runtime-rserve-proxified
      args:
        - RCLOUD_CONF=docker/stage/rcloud.conf
        - RCLOUD_RSERVE_PROXIFIED_CONF=docker/stage/rserve-proxified.conf
    volumes:
      - rcloud-data:/rcloud-data
      - rcloud-run:/rcloud-run

volumes:
  rcloud-run:
  rcloud-data:
